### ISSUE TITLE
Google Form for WheelPoser-IMU Dataset

### ISSUE THREAD

**Issue by bryanbocao** [axle-lab/WheelPoser#1]
Hi! Thanks for sharing the awesome code! I cannot access the WheelPoser-IMU Dataset. The form needs permission:

![Screenshot from 2024-10-29 21-40-41](https://github.com/user-attachments/assets/d594f45b-e41b-466a-897a-3bae880495b2)

Thanks!

**Comment by yunzhil** [comment]
Hi, thanks for letting us know! We have fixed it and now you should be able to submit your request!

**Comment by bryanbocao** [comment]
> Hi, thanks for letting us know! We have fixed it and now you should be able to submit your request!

@yunzhil I have signed the form. Thank you for fixing this issue!
